# Name of this GitHub Actions workflow.
name: Semgrep CE scan

on:
  # Scan in PRs:
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["main"]

permissions:
  # required for all workflows
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: semgrep-oss/scan
    # If you are self-hosting, change the following `runs-on` value: 
    runs-on: ubuntu-latest

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout. Use either v3 or v4.
      - name: Checkout repository
        uses: actions/checkout@v5
      
      # Run the "semgrep scan" command on the command line of the docker image.
      - name: Run Semgrep
        run: semgrep scan --config=r/all --sarif > semgrep.sarif

      - name: Replace text in a file using sed
        run: |
          sed -i 's/"Critical"\|"CRITICAL"/"9.0"/g' semgrep.sarif
          sed -i 's/"High"\|"HIGH"/"8.0"/g' semgrep.sarif
          sed -i 's/"Error"\|"ERROR"/"7.0"/g' semgrep.sarif
          sed -i 's/"Medium"\|"MEDIUM"/"5.0"/g' semgrep.sarif
          sed -i 's/"Warning"\|"WARNING"/"4.0"/g' semgrep.sarif
          sed -i 's/"Low"\|"LOW"/"1.0"/g' semgrep.sarif
          sed -i 's/"Info"\|"INFO"/"0.1"/g' semgrep.sarif
          jq '.runs[0].tool.driver.rules[].id |= .[0:250]' semgrep.sarif > cleaned_report.sarif

          
      # Upload the results to Github Code Scannning 
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: cleaned_report.sarif
        if: always()
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleaned_report.sarif
          path: cleaned_report.sarif
        if: always()





